export const DROPDOWNS_REQUEST = 'DROPDOWNS_REQUEST';
export const DROPDOWNS_SUCCESS = 'DROPDOWNS_SUCCESS';
export const DROPDOWNS_FAILURE = 'DROPDOWNS_FAILURE';

export const CHECK_DROPDOWNS_REQUEST = 'CHECK_DROPDOWNS_REQUEST';
export const CHECK_DROPDOWNS_SUCCESS = 'CHECK_DROPDOWNS_SUCCESS';
export const CHECK_DROPDOWNS_FAILURE = 'CHECK_DROPDOWNS_FAILURE';

export const SIMULATE_ORDER_REQUEST = 'SIMULATE_ORDER_REQUEST';
export const SIMULATE_ORDER_SUCCESS = 'SIMULATE_ORDER_SUCCESS';
export const SIMULATE_ORDER_FAILURE = 'SIMULATE_ORDER_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const UPDATE_VALUE = 'UPDATE_VALUE';

export const SELECT_HAS_SCORES = 'SELECT_HAS_SCORES';
export const SET_BOX_SCORES = 'SET_BOX_SCORES';
export const SET__BOX_FEFCOSHEET = 'SET__BOX_FEFCOSHEET';
