export const SELECTIONS_REQUEST = 'SELECTIONS_REQUEST';
export const SELECTIONS_SUCCESS = 'SELECTIONS_SUCCESS';
export const SELECTIONS_FAILURE = 'SELECTIONS_FAILURE';

export const CHECK_SELECTIONS_REQUEST = 'CHECK_SELECTIONS_REQUEST';
export const CHECK_SELECTIONS_SUCCESS = 'CHECK_SELECTIONS_SUCCESS';
export const CHECK_SELECTIONS_FAILURE = 'CHECK_SELECTIONS_FAILURE';

export const SIMULATE_ORDER_REQUEST = 'SIMULATE_ORDER_REQUEST';
export const SIMULATE_ORDER_SUCCESS = 'SIMULATE_ORDER_SUCCESS';
export const SIMULATE_ORDER_FAILURE = 'SIMULATE_ORDER_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const UPDATE_VALUE = 'UPDATE_VALUE';
